m4_include(macros/m4_ax_cxx_compile_stdcxx_11.m4)
m4_include(macros/m4_ax_boost_base.m4)
m4_include(macros/ax_x86_64_check.m4)
m4_include(macros/m4_ax_check_compile_flag.m4)
m4_include(macros/m4_ax_boost_thread.m4)
m4_include(macros/m4_ax_boost_iostreams.m4)
m4_include(macros/m4_ax_boost_system.m4)
m4_include(macros/autotroll.m4)
